### ISSUE TITLE
VS Code extension doesn't find spectral on my machine

### ISSUE THREAD

**Issue by vladyslav-cherednychenko** [SpectralOps/vscode-extension#1]
Hello,
I installed spectral via `curl -L https://app.spectralops.io/latest/sh?dsn=https://spu-XXX@app.spectralops.io | sh`.  
Then I installed the extension in the VS Code and got the message "...We noticed that Spectral is not installed on your machine..."
  
I am using Mac OS 10.15.7,  
The spectral binary is located in `/usr/local/bin/spectral`.  
My shell is `zsh`.

**Comment by guylev008** [comment]
Hi @vladyslav-cherednychenko 
Try downloading spectral from here:
https://get.spectralops.io/latest/x/sh
Let us know if the issue still persists

**Comment by vladyslav-cherednychenko** [comment]
I get the following output:
```
sh: line 1: {error:invalid Spectral DSN. You sent: https://spu-REDACTED@app.spectralops.io. A valid Spectral DSN looks like this: https://spk-6cdd6e********************5fcf6c@get.spectralops.io. Please make sure you're using a valid Spectral DSN. See your Spectral DSN in https://get.spectralops.io/settings/team or consult our integration guide at https://get.spectralops.io/sources}: No such file or directory
```

I tried both the "Team Key" and the DSN I copied from our settings page

**Comment by guylev008** [comment]
@vladyslav-cherednychenko Try this:
curl -L https://get.spectralops.io/latest/x/sh | sh

**Comment by vladyslav-cherednychenko** [comment]
That works, thanks!  
But it's strange to me that I had this issue while spectral was working just fine from the command line
