### ISSUE TITLE
Request for option for the Visual Studio IDE plugin to run engines by license

### ISSUE THREAD

**Issue by hakksawwcp** [SpectralOps/vscode-extension#4]
Spectral is limited to run based on assets and executions, so there are parameters for its execution that allows a developer to run unlimited IAC scans. Also, some users may only be interested in seeing returns for secrets, IAC and now OpenSource seperately.

But the IDE appears to always execute IAC and secrets.

Request is to allow for the following as selectable scan types:
--engines iac 
--engines secrets
--engines oss

And the whole shebang:
--engines secrets,iac,oss

At present, the invocation is hardcoded in:
spectral-agent-service.ts

  public scan(scanPath: string): Promise<any> {
    return new Promise(async (resolve, reject) => {
      const dsn = await SecretStorageService.getInstance().get(SPECTRAL_DSN)
      const outputFileName = 'output.txt'
      const spectralArgs = [
        '--nobanners',
        'scan',
        '--include-tags',
        **'base,iac',**
        '--nosend',
        '--ok',
        '--internal-output',
        outputFileName,
      ]

**Comment by guylev008** [comment]
Hi @hakksawwcp 
It's on our roadmap. Would you like to open a PR with a solution?
